const { createCanvas, loadImage } = require("canvas");

const WIDTH = 1200;
const BASE_HEIGHT = 320;
const CARD_HEIGHT = 92;
const MAX_ROWS_PER_IMAGE = 18;

function clampText(ctx, text, maxWidth) {
  if (!text) return "";
  let result = text;
  while (ctx.measureText(result).width > maxWidth && result.length > 0) {
    result = result.slice(0, -1);
  }
  return result;
}

function drawBackground(ctx, height) {
  const gradient = ctx.createLinearGradient(0, 0, WIDTH, height);
  gradient.addColorStop(0, "#0f172a");
  gradient.addColorStop(0.35, "#1e293b");
  gradient.addColorStop(0.7, "#312e81");
  gradient.addColorStop(1, "#4c1d95");
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, WIDTH, height);

  ctx.globalAlpha = 0.04;
  for (let i = 0; i < 2800; i++) {
    const size = Math.random() * 2;
    ctx.fillStyle = Math.random() > 0.5 ? "#ffffff" : "#312e81";
    ctx.fillRect(Math.random() * WIDTH, Math.random() * height, size, size);
  }
  ctx.globalAlpha = 1;

  ctx.save();
  ctx.globalAlpha = 0.12;
  const bubbles = [
    { x: 160, y: 140, r: 140, color: "#60a5fa" },
    { x: WIDTH - 140, y: 120, r: 200, color: "#f472b6" },
    { x: WIDTH - 180, y: height - 200, r: 180, color: "#a855f7" },
    { x: 220, y: height - 140, r: 160, color: "#22d3ee" }
  ];
  bubbles.forEach(({ x, y, r, color }) => {
    ctx.beginPath();
    ctx.fillStyle = color;
    ctx.arc(x, y, r, 0, Math.PI * 2);
    ctx.fill();
  });
  ctx.restore();
}

function drawHeader(ctx, opts) {
  const { groupName, groupId, page, totalPages, totalMembers } = opts;
  ctx.save();

  ctx.fillStyle = "rgba(15, 23, 42, 0.55)";
  ctx.beginPath();
  ctx.roundRect(46, 38, WIDTH - 92, 160, 28);
  ctx.fill();

  const borderGradient = ctx.createLinearGradient(46, 38, WIDTH - 46, 198);
  borderGradient.addColorStop(0, "rgba(96, 165, 250, 0.6)");
  borderGradient.addColorStop(0.5, "rgba(244, 114, 182, 0.55)");
  borderGradient.addColorStop(1, "rgba(129, 140, 248, 0.55)");
  ctx.strokeStyle = borderGradient;
  ctx.lineWidth = 2.5;
  ctx.stroke();

  ctx.fillStyle = "#f8fafc";
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.shadowColor = "rgba(59, 130, 246, 0.65)";
  ctx.shadowBlur = 18;
  ctx.font = "bold 60px 'Poppins', sans-serif";
  ctx.fillText("MEMBER LIST", WIDTH / 2, 100);

  ctx.shadowBlur = 0;
  ctx.font = "600 26px 'Inter', sans-serif";
  const subLine = `${groupName || "Không rõ tên"} • ID: ${groupId}`;
  ctx.fillStyle = "rgba(226, 232, 240, 0.9)";
  ctx.fillText(subLine, WIDTH / 2, 150);

  ctx.font = "bold 22px 'Inter', sans-serif";
  ctx.fillStyle = "#22d3ee";
  ctx.fillText(`Tổng thành viên: ${totalMembers} • Trang ${page}/${totalPages}`, WIDTH / 2, 185);

  ctx.restore();
}

function drawFooter(ctx, height) {
  ctx.save();
  const footerGradient = ctx.createLinearGradient(0, height - 60, WIDTH, height - 60);
  footerGradient.addColorStop(0, "rgba(59, 130, 246, 0.25)");
  footerGradient.addColorStop(1, "rgba(236, 72, 153, 0.25)");
  ctx.fillStyle = footerGradient;
  ctx.fillRect(0, height - 60, WIDTH, 60);

  ctx.fillStyle = "rgba(226, 232, 240, 0.75)";
  ctx.font = "600 18px 'Inter', sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Generated by BONZ Bot • listmembers", WIDTH / 2, height - 28);
  ctx.restore();
}

async function loadAvatar(url) {
  if (!url || typeof url !== "string" || !url.startsWith("http")) return null;
  try {
    return await loadImage(url);
  } catch (error) {
    console.warn("[groupmember-canvas] load avatar failed:", error?.message || error);
    return null;
  }
}

function drawMemberCard(ctx, member, index, avatars, y) {
  const cardX = 70;
  const cardWidth = WIDTH - 140;
  const cardHeight = CARD_HEIGHT;
  const avatarSize = 70;
  const paddingX = cardX + 24;

  ctx.save();
  ctx.fillStyle = "rgba(15, 23, 42, 0.7)";
  ctx.beginPath();
  ctx.roundRect(cardX, y, cardWidth, cardHeight, 24);
  ctx.fill();

  const borderGradient = ctx.createLinearGradient(cardX, y, cardX + cardWidth, y + cardHeight);
  borderGradient.addColorStop(0, "rgba(59, 130, 246, 0.45)");
  borderGradient.addColorStop(1, "rgba(236, 72, 153, 0.45)");
  ctx.strokeStyle = borderGradient;
  ctx.lineWidth = 1.8;
  ctx.stroke();

  const avatarX = paddingX;
  const avatarY = y + (cardHeight - avatarSize) / 2;
  ctx.save();
  ctx.beginPath();
  ctx.arc(avatarX + avatarSize / 2, avatarY + avatarSize / 2, avatarSize / 2, 0, Math.PI * 2);
  ctx.clip();
  const avatarImage = avatars[index];
  if (avatarImage) {
    ctx.drawImage(avatarImage, avatarX, avatarY, avatarSize, avatarSize);
  } else {
    const colorGradient = ctx.createLinearGradient(avatarX, avatarY, avatarX + avatarSize, avatarY + avatarSize);
    colorGradient.addColorStop(0, "#38bdf8");
    colorGradient.addColorStop(1, "#f472b6");
    ctx.fillStyle = colorGradient;
    ctx.fillRect(avatarX, avatarY, avatarSize, avatarSize);
    ctx.fillStyle = "#0f172a";
    ctx.font = "bold 30px 'Inter', sans-serif";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    const initial = (member.displayName || member.uid || "?")
      .toString()
      .trim()
      .charAt(0)
      .toUpperCase();
    ctx.fillText(initial || "?", avatarX + avatarSize / 2, avatarY + avatarSize / 2);
  }
  ctx.restore();

  ctx.fillStyle = "rgba(94, 234, 212, 0.55)";
  ctx.beginPath();
  ctx.roundRect(paddingX + avatarSize + 10, y + 18, 48, 28, 14);
  ctx.fill();
  ctx.fillStyle = "#5eead4";
  ctx.font = "bold 18px 'Inter', sans-serif";
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(String(member.index + 1), paddingX + avatarSize + 34, y + 32);

  const textStartX = paddingX + avatarSize + 70;
  const nameMaxWidth = WIDTH - textStartX - 180;
  ctx.fillStyle = "#e2e8f0";
  ctx.font = "bold 26px 'Poppins', sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  const rawName = member.displayName || `UID ${member.uid.slice(-6)}`;
  const name = clampText(ctx, rawName, nameMaxWidth);
  ctx.fillText(`${member.index + 1}. ${name}`, textStartX, y + 18);

  ctx.font = "18px 'Inter', sans-serif";
  ctx.fillStyle = "rgba(226, 232, 240, 0.85)";
  ctx.fillText(`UID: ${member.uid}`, textStartX, y + 52);

  if (member.nickname && member.nickname !== member.displayName) {
    ctx.fillStyle = "rgba(167, 139, 250, 0.9)";
    ctx.font = "17px 'Inter', sans-serif";
    ctx.fillText(`Nickname: ${member.nickname}`, textStartX, y + 76);
  }

  ctx.restore();
}

async function createMemberListImage({ groupId, groupName, members }) {
  const totalMembers = Array.isArray(members) ? members.length : 0;
  if (totalMembers === 0) {
    const height = BASE_HEIGHT;
    const canvas = createCanvas(WIDTH, height);
    const ctx = canvas.getContext("2d");
    drawBackground(ctx, height);
    drawHeader(ctx, { groupName, groupId, page: 1, totalPages: 1, totalMembers: 0 });
    ctx.fillStyle = "rgba(244, 244, 255, 0.9)";
    ctx.font = "bold 32px 'Inter', sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("Không có thành viên để hiển thị", WIDTH / 2, height / 2 + 30);
    drawFooter(ctx, height);
    return [{ buffer: canvas.toBuffer("image/png"), page: 1 }];
  }

  const pages = [];
  const totalPages = Math.ceil(totalMembers / MAX_ROWS_PER_IMAGE);

  for (let page = 0; page < totalPages; page++) {
    const slice = members.slice(page * MAX_ROWS_PER_IMAGE, (page + 1) * MAX_ROWS_PER_IMAGE);
    const dynamicHeight = BASE_HEIGHT + slice.length * (CARD_HEIGHT + 16);
    const height = Math.min(dynamicHeight, 1800);
    const canvas = createCanvas(WIDTH, height);
    const ctx = canvas.getContext("2d");

    drawBackground(ctx, height);
    drawHeader(ctx, {
      groupName,
      groupId,
      page: page + 1,
      totalPages,
      totalMembers
    });

    const avatarPromises = slice.map((member) => loadAvatar(member.avatar));
    const avatars = await Promise.all(avatarPromises);

    let currentY = 230;
    slice.forEach((member) => {
      drawMemberCard(ctx, member, member.index, avatars, currentY);
      currentY += CARD_HEIGHT + 16;
    });

    drawFooter(ctx, height);
    pages.push({ buffer: canvas.toBuffer("image/png"), page: page + 1 });
  }

  return pages;
}

module.exports = {
  createMemberListImage
};
